-- db: database
-- wv: widest view
drop database if exists DB_WV;

create database if not exists DB_WV;

use DB_WV;

create table if not exists FUNCIONARIO
(
    CODIGO      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME        VARCHAR (255) NOT NULL,
    NOME_SOCIAL VARCHAR (255) NOT NULL,
    GENERO      CHAR NOT NULL,
    RG          VARCHAR(12) NOT NULL,
    CPF         CHAR(11) NOT NULL,
    NASCIMENTO  DATE NOT NULL,
    TELEFONE    VARCHAR(15),
    CEL         VARCHAR(15),
    EMAIL       VARCHAR (255) NOT NULL,
    NIVELACESSO INT NOT NULL,
    SENHA       VARCHAR(10),
    ATIVO       BOOLEAN NOT NULL DEFAULT TRUE
);

create table if not exists ESPECIALIDADE
(
    CODIGO  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME    VARCHAR (255) NOT NULL
);

-- AGRE_ESP_FUNC: Agragação entre especialidade e funcionário
create table if not exists AGRE_ESP_FUNC
(
    CODIGO                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODIGO_ESPECIALIDADE    INT NOT NULL,
    CODIGO_FUNCIONARIO      INT NOT NULL
);

-- REP_CLIENTE: Representante do cliente
create table if not exists REP_CLIENTE
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME            VARCHAR (255) NOT NULL,
    NOME_SOCIAL     VARCHAR (255) NOT NULL,
    CPF             CHAR(11) NOT NULL,
    GENERO          VARCHAR(2) NOT NULL,
    TELEFONE        VARCHAR(15) NOT NULL,
    CEL             VARCHAR(15) NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL
);

create table if not exists CLIENTE
(
    CODIGO                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME                    VARCHAR (255) NOT NULL,
    CNPJ                    VARCHAR(14) NOT NULL,
    CODIGO_REPRESENTANTE    INT NOT NULL
);

create table if not exists SERVICO
(
    CODIGO      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME        VARCHAR (255) NOT NULL,
    DESCRICAO   TEXT NOT NULL,
    ATIVO       BOOLEAN NOT NULL DEFAULT TRUE
);

-- CONTRATO_MANU: Contrato de manutenção
create table if not exists CONTRATO_MANU
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_INICIO     DATE NOT NULL,
    DATA_FINAL      DATE NOT NULL,
    ATIVO           BOOLEAN NOT NULL DEFAULT TRUE,
    CODIGO_CLIENTE  INT NOT NULL
);

create table if not exists PROJETO
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO       TEXT NOT NULL,
    ATIVO           BOOLEAN NOT NULL DEFAULT TRUE,
    CODIGO_CLIENTE  INT NOT NULL
);

create table if not exists AGENDA
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DIA             DATE NOT NULL,
    NOME            VARCHAR (255) NOT NULL,
    DESCRICAO       TEXT NOT NULL,
    CODIGO_PROJETO  INT NOT NULL
);

-- AGRE_FUNC_PROJ: Agregação entre funcionário e projeto
create table if not exists AGRE_FUNC_PROJ
(
    CODIGO              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODIGO_FUNCIONARIO  INT NOT NULL,
    CODIGO_PROJETO      INT NOT NULL,
    CODIGO_SERVICO      INT NOT NULL
);

-- ORCAMENTO_PROJ: Orçamento do projeto 
create table if not exists ORCAMENTO_PROJ
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME            VARCHAR (255) NOT NULL,
    VALOR           NUMERIC (18, 2) NOT NULL,
    CODIGO_SERVICO   INT NOT NULL,
    CODIGO_PROJETO  INT NOT NULL
);

create table if not exists RELATORIO
(
    CODIGO          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DIA             DATE NOT NULL,
    DESCRICAO       TEXT NOT NULL,
    CODIGO_PROJETO  INT NOT NULL
);

create table if not exists DEMISSAO
(
    CODIGO              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DIA                 DATE NOT NULL,
    JUSTIFICATIVA       TEXT NOT NULL,
    CODIGO_FUNCIONARIO  INT NOT NULL,
    CODIGO_RELATORIO    INT NOT NULL
);

-- ANOTACAO_PROJ: Anotação/comentário em um projeto
-- CÓDIGO_FUNC_PROJ: Código derivado da tabela de agregação entre funcionário e projeto
create table if not exists ANOTACAO_PROJ
(
    CODIGO              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO              VARCHAR (255) NOT NULL,
    ANOTACAO            TEXT NOT NULL,
    HORARIO             DATETIME NOT NULL,
    CODIGO_FUNC_PROJ    INT,
    CODIGO_PROJETO      INT NOT NULL,
    CODIGO_FUNCIONARIO  INT NOT NULL
);

-- RESPOSTA_ANOT: Resposta para uma anotação/comentário
create table if not exists RESPOSTA_ANOT
(
	CODIGO				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RESPOSTA			TEXT NOT NULL,
    HORARIO				DATETIME NOT NULL,
    CODIGO_FUNCIONARIO	INT NOT NULL,
    CODIGO_ANOTACAO		INT NOT NULL
);

ALTER TABLE AGRE_ESP_FUNC ADD FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO);
ALTER TABLE AGRE_ESP_FUNC ADD FOREIGN KEY (CODIGO_ESPECIALIDADE) REFERENCES ESPECIALIDADE(CODIGO);

ALTER TABLE CLIENTE ADD FOREIGN KEY (CODIGO_REPRESENTANTE) REFERENCES REP_CLIENTE(CODIGO);

ALTER TABLE CONTRATO_MANU ADD FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO);

ALTER TABLE PROJETO ADD FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO);

ALTER TABLE AGENDA ADD FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO(CODIGO);

ALTER TABLE AGRE_FUNC_PROJ ADD FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO);
ALTER TABLE AGRE_FUNC_PROJ ADD FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO(CODIGO);
ALTER TABLE AGRE_FUNC_PROJ ADD FOREIGN KEY (CODIGO_SERVICO) REFERENCES SERVICO(CODIGO);

ALTER TABLE ORCAMENTO_PROJ ADD FOREIGN KEY (CODIGO_SERVICO) REFERENCES SERVICO(CODIGO);
ALTER TABLE ORCAMENTO_PROJ ADD FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO(CODIGO);

ALTER TABLE RELATORIO ADD FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO(CODIGO);

ALTER TABLE DEMISSAO ADD FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO);
ALTER TABLE DEMISSAO ADD FOREIGN KEY (CODIGO_RELATORIO) REFERENCES RELATORIO(CODIGO);

ALTER TABLE ANOTACAO_PROJ ADD FOREIGN KEY (CODIGO_FUNC_PROJ) REFERENCES AGRE_FUNC_PROJ(CODIGO);
ALTER TABLE ANOTACAO_PROJ ADD FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO);
ALTER TABLE ANOTACAO_PROJ ADD FOREIGN KEY (CODIGO_PROJETO) REFERENCES PROJETO (CODIGO);

ALTER TABLE RESPOSTA_ANOT ADD FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO);
ALTER TABLE RESPOSTA_ANOT ADD FOREIGN KEY (CODIGO_ANOTACAO) REFERENCES ANOTACAO_PROJ(CODIGO);

/* TESTS */

insert into funcionario(nome,nome_social,genero,rg,cpf,nascimento,telefone,cel,email,nivelacesso,senha,ativo)
values ('ADMININISTRO', 'admBrabo', 'M', '5', '2','2004-02-08', '2', '2', 'adm@gmail.com', 1, 'adm', 1 ),
	   ('nao_adm', 'nao_adm', 'M', '5', '2','2004-02-08', '2', '2', 'nao_adm@gmail.com', 0, 'adm', 1 );
